name = "aurora-keys"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "keys.dallaswebstudio.net", custom_domain = true }
]

[[kv_namespaces]]
binding = "AURORA_KEYS"
id = "364ae86421b64dcc8102b91e52c10e56"
